// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Js_array = require("rescript/lib/js/js_array.js");
var Js_string = require("rescript/lib/js/js_string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Belt_Array.map(Belt_Array.map(Belt_Array.map(Belt_Array.keep(Fs.readFileSync("src/day_8/test", "utf8").split("\n"), (function (e) {
                    return e !== "";
                  })), (function (param) {
                return Js_string.split("", param);
              })), (function (param) {
            return Js_array.map(Belt_Int.fromString, param);
          })), (function (param) {
        return Js_array.map((function (prim) {
                      return prim;
                    }), param);
      }));

var count = {
  contents: 0
};

console.log(Belt_Array.mapWithIndex(input, (function (x, line) {
            return Belt_Array.mapWithIndex(line, (function (y, e) {
                          Belt_Array.map(input, (function (__x) {
                                  return __x[y];
                                }));
                        }));
          })));

var len = 5;

exports.input = input;
exports.count = count;
exports.len = len;
/* input Not a pure module */
