// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

console.log(Belt_Array.keep(Belt_Array.keep(Fs.readFileSync("./src/day_4/input", "utf8").split("\n"), (function (e) {
                return e !== "";
              })), (function (e) {
            var splits = Belt_Array.map(Belt_Array.flatMap(e.split(","), (function (e) {
                        return e.split("-");
                      })), Belt_Int.fromString);
            var a = splits[0];
            var b = splits[1];
            var c = splits[2];
            var d = splits[3];
            return Math.imul(Caml_obj.compare(a, c), Caml_obj.compare(b, d)) <= 0;
          })).length);

/*  Not a pure module */
