// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Caml = require("rescript/lib/js/caml.js");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

console.log(Belt_Array.keep(Belt_Array.keep(Fs.readFileSync("./src/day_4/input", "utf8").split("\n"), (function (e) {
                return e !== "";
              })), (function (e) {
            var splits = Belt_Array.map(Belt_Array.flatMap(e.split(","), (function (e) {
                        return e.split("-");
                      })), Belt_Int.fromString);
            var a = splits[0];
            var b = splits[1];
            var c = splits[2];
            var d = splits[3];
            return (((Math.imul(Caml.int_compare(a, c), Caml.int_compare(b, c)) + Math.imul(Caml.int_compare(a, d), Caml.int_compare(b, d)) | 0) + Math.imul(Caml.int_compare(c, a), Caml.int_compare(d, a)) | 0) + Math.imul(Caml.int_compare(c, b), Caml.int_compare(d, b)) | 0) !== 4;
          })).length);

/*  Not a pure module */
