// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_MutableMapString = require("rescript/lib/js/belt_MutableMapString.js");

var input = "bvwbjplbgvbhsrlpgdmjqwftvncz";

console.log(Belt_Array.reduceWithIndex(input.split(""), Belt_MutableMapString.make(undefined), (function (acc, cur, i) {
            var e = Belt_MutableMapString.get(acc, cur);
            if (e !== undefined) {
              Belt_MutableMapString.forEach(acc, (function (k, v) {
                      console.log(k);
                    }));
              Belt_MutableMapString.set(acc, cur, i);
            } else {
              Belt_MutableMapString.set(acc, cur, i);
            }
            return acc;
          })));

exports.input = input;
/*  Not a pure module */
