// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Js_array = require("rescript/lib/js/js_array.js");
var Js_string = require("rescript/lib/js/js_string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Caml_int32 = require("rescript/lib/js/caml_int32.js");

var input = Belt_Array.flatMap(Belt_Array.map(Belt_Array.map(Belt_Array.map(Belt_Array.keep(Fs.readFileSync("src/day_8/test", "utf8").split("\n"), (function (e) {
                        return e !== "";
                      })), (function (param) {
                    return Js_string.split("", param);
                  })), (function (param) {
                return Js_array.map(Belt_Int.fromString, param);
              })), (function (param) {
            return Js_array.map((function (prim) {
                          return prim;
                        }), param);
          })), (function (a) {
        return a;
      }));

var length = Math.sqrt(input.length) | 0;

console.log(Belt_Array.mapWithIndex(input, (function (i, e) {
            Caml_int32.div(i, length);
            Caml_int32.mod_(i, length);
            return e;
          })));

exports.input = input;
exports.length = length;
/* input Not a pure module */
