// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var input = Belt_Array.keep(Fs.readFileSync("src/day_5/test", "utf8").split("\n"), (function (e) {
        return e !== "";
      }));

var packages = Belt_Array.slice(input, 0, 3);

var action = Belt_Array.slice(input, 4, 1);

exports.input = input;
exports.packages = packages;
exports.action = action;
/* input Not a pure module */
